const routes = {
    home: '',
    chamsoc: '/lamdep',
    timkiem: '/tim-kiem',
    themdiachi: '/them-dia-chi',
    thanhtoan: '/thanh-toan',
    maymoc: '/maymoc',
    tuixach: '/tuixach',
    phukien: '/phukien',
    dodung: '/dodung',
    cart: '/gio-hang',
    detail: '/detail/:paramValue/:idProduct',
    sitemap: '/sitemap',
    shopPage: `/shop/:paramValue`,
    shopSanpham: `/shop/:paramValue/san-pham`,
    shopBoSuuTap: `/shop/:paramValue/bo-suu-tap`,
    shopGiaTot: `/shop/:paramValue/gia-tot-hom-nay`,
    shopThongTin: `/shop/:paramValue/thong-tin-shop`,
    findProd: `/:paramValue`,
    shopPageProduct: `/shop/:paramValue/san-pham`,
    thanhtoanthanhcong: '/thanh-toan-thanh-cong',
};
export default routes;
